version: '3.8'

services:
  dockerwdb:
    image: dockerwdb
    build:
      context: .
      dockerfile: DockerWDb/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"  # Esto asegura que siempre use el puerto 5000 en localhost
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
